In [1]:
from pathlib import Path
DATASET_DIR = Path.cwd().parent / "dataset" 
DATASET_DIR

WindowsPath('c:/Applications/Github Projects/hackerrank-orchestrate-august26-main/hackerrank-orchestrate-august26-main/dataset')

In [2]:
import pandas as pd

business_acc_data = pd.read_csv(str(DATASET_DIR) + "/business_accounts.csv")
daily_notification_data = pd.read_csv(str(DATASET_DIR) + "/daily_notification_summary.csv")
group_members_data = pd.read_csv(str(DATASET_DIR) + "/group_members.csv")
groups_data = pd.read_csv(str(DATASET_DIR) + "/groups.csv")
images_data = pd.read_csv(str(DATASET_DIR) + "/images.csv")
message_events_data = pd.read_csv(str(DATASET_DIR) + "/message_events.csv")
message_history_data = pd.read_csv(str(DATASET_DIR) + "/message_history.csv")
user_business_history_data = pd.read_csv(str(DATASET_DIR) + "/user_business_history.csv")
users_data = pd.read_csv(str(DATASET_DIR) + "/users.csv")
voice_notes_data = pd.read_csv(str(DATASET_DIR) + "/voice_notes.csv")
messages_data = pd.read_csv(str(DATASET_DIR) + "/messages.csv")

In [3]:
messages_data.head()

,message_id,user_id,conversation_type,group_id,business_id,sender_user_id,created_at,message_text,media_type,media_id,forwarded_count
0,msg_023,u_002,business,NaN,business_002,NaN,2026-07-30 22:19,"Important Information\n\nDear Customer,\n\nYou...",NaN,NaN,0
1,msg_091,u_028,personal,NaN,NaN,u_049,2026-07-24 18:07,Your workspace access will expire today. Reply...,NaN,NaN,0
2,msg_090,u_034,personal,NaN,NaN,u_050,2026-07-20 15:02,"Hi, is this Arun from Bluebell Apartments? I g...",NaN,NaN,0
3,msg_048,u_011,group,group_011,NaN,u_053,2026-07-20 08:51,Admin notice: penalty list is being finalized ...,NaN,NaN,2
4,msg_040,u_007,group,group_001,NaN,u_051,2026-07-31 08:02,@u_007 forward this to ten people for blessing...,NaN,NaN,7

In [4]:
users_data.head()

,user_id,do_not_disturb_window,messages_opened_30d,messages_replied_30d,notifications_dismissed_30d,messages_reported_30d
0,u_001,22:00-07:00,45,8,14,2
1,u_002,23:00-08:00,52,11,19,4
2,u_003,21:30-07:30,59,14,24,1
3,u_004,00:00-06:30,66,17,29,3
4,u_005,22:30-07:00,73,20,34,0

In [5]:
messages_df = messages_data.copy(deep=True)
messages_df.rename(columns={"created_at":"message_created_at","media_id":"message_media_id","media_type":"message_media_type","forwarded_count":"message_forwarded_count", "conversation_type":"message_conversation_type"}, inplace=True)
users_df = users_data.copy(deep=True)
users_df.rename(columns={"notifications_dismissed_30d":"total_notifications_dismissed_30d","messages_reported_30d":"total_messages_reported_30d","do_not_disturb_window":"users_do_not_disturb_window", "messages_opened_30d":"users_total_messages_opened_30d","messages_replied_30d":"users_total_messages_replied_30d","notifications_dismissed_30d":"users_total_notifications_dismissed_30d", "messages_reported_30d":"users_total_messages_reported_30d"}, inplace=True)
messages_df = messages_df.merge(users_df, how="left", on="user_id")
messages_df.head()

,message_id,user_id,message_conversation_type,group_id,business_id,sender_user_id,message_created_at,message_text,message_media_type,message_media_id,message_forwarded_count,users_do_not_disturb_window,users_total_messages_opened_30d,users_total_messages_replied_30d,users_total_notifications_dismissed_30d,users_total_messages_reported_30d
0,msg_023,u_002,business,NaN,business_002,NaN,2026-07-30 22:19,"Important Information\n\nDear Customer,\n\nYou...",NaN,NaN,0,23:00-08:00,52,11,19,4
1,msg_091,u_028,personal,NaN,NaN,u_049,2026-07-24 18:07,Your workspace access will expire today. Reply...,NaN,NaN,0,23:30-07:30,42,5,45,1
2,msg_090,u_034,personal,NaN,NaN,u_050,2026-07-20 15:02,"Hi, is this Arun from Bluebell Apartments? I g...",NaN,NaN,0,21:30-06:30,84,23,23,3
3,msg_048,u_011,group,group_011,NaN,u_053,2026-07-20 08:51,Admin notice: penalty list is being finalized ...,NaN,NaN,2,21:30-06:30,92,28,18,1
4,msg_040,u_007,group,group_001,NaN,u_051,2026-07-31 08:02,@u_007 forward this to ten people for blessing...,NaN,NaN,7,22:00-07:00,44,6,68,2

In [6]:
group_members_data.head()

,group_id,user_id,role,joined_at,messages_sent_30d,messages_read_30d,replies_sent_30d,notifications_dismissed_30d,group_muted_by_user
0,group_001,u_001,admin,2023-06-13,2,2,0,4,1
1,group_001,u_002,member,2023-09-20,4,4,1,3,0
2,group_001,u_003,member,2023-12-27,2,3,1,6,1
3,group_001,u_007,member,2023-03-07,1,1,0,9,1
4,group_001,u_011,member,2023-06-14,0,3,0,5,1

In [7]:
groups_data.head()

,group_id,group_name,group_type,member_count,admin_count,created_at,messages_30d
0,group_001,Mehra Family,family,14,2,2023-02-11,92
1,group_002,Green Acres Society Notices,society,184,4,2024-01-19,742
2,group_003,International School Parents Group,school_group,96,3,2025-04-03,418
3,group_004,Checkout Platform Co-workers,coworker,28,3,2025-06-12,512
4,group_005,Myntra Marketplace,marketplace,241,1,2026-01-08,963

In [8]:
group_members_df = group_members_data.copy(deep=True)
group_members_df.rename(columns={"role":"group_role","notifications_dismissed_30d":"group_notifications_dismissed_30d","messages_sent_30d":"group_messages_sent_30d", "messages_read_30d":"group_messages_read_30d","replies_sent_30d":"group_replies_sent_30d", "joined_at":"group_joined_at"}, inplace=True)
groups_df = groups_data.copy(deep=True)
groups_df.rename(columns={"messages_30d":"group_total_messages_30d", "created_at":"group_created_at", "member_count":"group_member_count", "admin_count":"group_admin_count"}, inplace=True)
group_info_df = group_members_df.merge(groups_df, how="left", on="group_id")
group_info_df.head()

,group_id,user_id,group_role,group_joined_at,group_messages_sent_30d,group_messages_read_30d,group_replies_sent_30d,group_notifications_dismissed_30d,group_muted_by_user,group_name,group_type,group_member_count,group_admin_count,group_created_at,group_total_messages_30d
0,group_001,u_001,admin,2023-06-13,2,2,0,4,1,Mehra Family,family,14,2,2023-02-11,92
1,group_001,u_002,member,2023-09-20,4,4,1,3,0,Mehra Family,family,14,2,2023-02-11,92
2,group_001,u_003,member,2023-12-27,2,3,1,6,1,Mehra Family,family,14,2,2023-02-11,92
3,group_001,u_007,member,2023-03-07,1,1,0,9,1,Mehra Family,family,14,2,2023-02-11,92
4,group_001,u_011,member,2023-06-14,0,3,0,5,1,Mehra Family,family,14,2,2023-02-11,92

In [9]:
messages_df = messages_df.merge(group_info_df, how="left", on=["group_id", "user_id"])
messages_df.head()

,message_id,user_id,message_conversation_type,group_id,business_id,sender_user_id,message_created_at,message_text,message_media_type,message_media_id,...,group_messages_read_30d,group_replies_sent_30d,group_notifications_dismissed_30d,group_muted_by_user,group_name,group_type,group_member_count,group_admin_count,group_created_at,group_total_messages_30d
0,msg_023,u_002,business,NaN,business_002,NaN,2026-07-30 22:19,"Important Information\n\nDear Customer,\n\nYou...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,msg_091,u_028,personal,NaN,NaN,u_049,2026-07-24 18:07,Your workspace access will expire today. Reply...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,msg_090,u_034,personal,NaN,NaN,u_050,2026-07-20 15:02,"Hi, is this Arun from Bluebell Apartments? I g...",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,msg_048,u_011,group,group_011,NaN,u_053,2026-07-20 08:51,Admin notice: penalty list is being finalized ...,NaN,NaN,...,15.0,7.0,0.0,0.0,Society Maintenance Desk,society,118.0,2.0,2024-07-10,487.0
4,msg_040,u_007,group,group_001,NaN,u_051,2026-07-31 08:02,@u_007 forward this to ten people for blessing...,NaN,NaN,...,1.0,0.0,9.0,1.0,Mehra Family,family,14.0,2.0,2023-02-11,92.0

In [10]:
messages_df.columns

Index(['message_id', 'user_id', 'message_conversation_type', 'group_id',
       'business_id', 'sender_user_id', 'message_created_at', 'message_text',
       'message_media_type', 'message_media_id', 'message_forwarded_count',
       'users_do_not_disturb_window', 'users_total_messages_opened_30d',
       'users_total_messages_replied_30d',
       'users_total_notifications_dismissed_30d',
       'users_total_messages_reported_30d', 'group_role', 'group_joined_at',
       'group_messages_sent_30d', 'group_messages_read_30d',
       'group_replies_sent_30d', 'group_notifications_dismissed_30d',
       'group_muted_by_user', 'group_name', 'group_type', 'group_member_count',
       'group_admin_count', 'group_created_at', 'group_total_messages_30d'],
      dtype='str')

In [11]:
images_data.head()

  image_id                 file_path
0  img_001  media/images/img_001.jpg
1  img_002  media/images/img_002.jpg
2  img_003  media/images/img_003.jpg
3  img_004  media/images/img_004.jpg
4  img_005  media/images/img_005.jpg

In [12]:
images_df = images_data.copy(deep=True)
images_df.rename(columns={"file_path":"image_file_path"}, inplace=True)
messages_df = messages_df.merge(images_df, how="left", left_on="message_media_id", right_on="image_id")
messages_df.columns

Index(['message_id', 'user_id', 'message_conversation_type', 'group_id',
       'business_id', 'sender_user_id', 'message_created_at', 'message_text',
       'message_media_type', 'message_media_id', 'message_forwarded_count',
       'users_do_not_disturb_window', 'users_total_messages_opened_30d',
       'users_total_messages_replied_30d',
       'users_total_notifications_dismissed_30d',
       'users_total_messages_reported_30d', 'group_role', 'group_joined_at',
       'group_messages_sent_30d', 'group_messages_read_30d',
       'group_replies_sent_30d', 'group_notifications_dismissed_30d',
       'group_muted_by_user', 'group_name', 'group_type', 'group_member_count',
       'group_admin_count', 'group_created_at', 'group_total_messages_30d',
       'image_id', 'image_file_path'],
      dtype='str')

In [13]:
business_acc_data.head()

,business_id,display_name,brand_name,category,verified,official_domain,domain_used_by_sender,account_age_days,messages_sent_30d,user_reports_30d,domain_used_by_sender_age_days
0,business_001,Amazon India,Amazon India,ecommerce_delivery,1,amazon.in,amazon.in,937,1243,3,729
1,business_051,Bank of America,Bank of America,bank,1,bankofamerica.com,bankofamerica.com,2787,3393,8,2179
2,business_011,Myntra,Myntra,fashion,1,myntra.com,myntra.com,1307,1673,4,1019
3,business_061,Grab,Grab,ride_booking,1,grab.com,grab.com,3157,3823,9,2469
4,business_021,Airtel,Airtel,telecom,1,airtel.in,airtel.in,1677,2103,5,1309

In [14]:
business_acc_df = business_acc_data.copy(deep=True)
business_acc_df.rename(columns={"display_name":"business_display_name","brand_name":"business_brand_name", "category":"business_category","verified":"is_business_verified","official_domain":"business_official_domain", "domain_used_by_sender":"business_domain_used_by_sender","account_age_days":"business_account_age_days","messages_sent_30d":"business_messages_sent_30d","user_reports_30d":"business_user_reports_30d","domain_used_by_sender_age_days":"business_domain_used_by_sender_age_days"}, inplace=True)
messages_df = messages_df.merge(business_acc_df, how="left", on="business_id")

In [15]:
user_business_history_data.head()

,user_id,business_id,why_user_knows_account,last_activity_at,allows_promotions,promotions_opted_out_at,activity_count_180d,messages_opened_30d,messages_dismissed_30d,messages_replied_30d,last_reply_at
0,u_001,business_001,recent_grocery_delivery,2026-07-17 23:55,0,NaN,3,5,1,0,NaN
1,u_001,business_003,old_sale_subscription,2026-05-11 12:40,0,2026-07-17 23:55,4,1,7,0,NaN
2,u_002,business_003,active_sale_subscription,2026-07-17 23:55,1,NaN,8,7,0,1,2026-07-17 23:55
3,u_002,business_002,active_bank_account,2026-06-14 10:25,0,NaN,3,6,0,2,2026-06-14 10:25
4,u_003,business_004,upcoming_clinic_appointment,2026-07-17 23:55,0,NaN,2,6,1,1,2026-07-17 23:55

In [16]:
user_business_history_df = user_business_history_data.copy(deep=True)
user_business_history_df.rename(columns={"why_user_knows_account":"why_user_knows_business_account", "last_activity_at":"user_business_last_activity", "allows_promotions":"business_allows_promotions", "promotions_opted_out_at":"user_business_promotions_opted_out_at","activity_count_180d":"user_business_activity_count_180d","messages_opened_30d":"user_business_messages_opened_30d","messages_dismissed_30d":"user_business_messages_dismissed_30d","messages_replied_30d":"user_business_messages_replied_30d","last_reply_at":"user_business_last_reply_at"}, inplace=True)
user_business_history_df.head()

,user_id,business_id,why_user_knows_business_account,user_business_last_activity,business_allows_promotions,user_business_promotions_opted_out_at,user_business_activity_count_180d,user_business_messages_opened_30d,user_business_messages_dismissed_30d,user_business_messages_replied_30d,user_business_last_reply_at
0,u_001,business_001,recent_grocery_delivery,2026-07-17 23:55,0,NaN,3,5,1,0,NaN
1,u_001,business_003,old_sale_subscription,2026-05-11 12:40,0,2026-07-17 23:55,4,1,7,0,NaN
2,u_002,business_003,active_sale_subscription,2026-07-17 23:55,1,NaN,8,7,0,1,2026-07-17 23:55
3,u_002,business_002,active_bank_account,2026-06-14 10:25,0,NaN,3,6,0,2,2026-06-14 10:25
4,u_003,business_004,upcoming_clinic_appointment,2026-07-17 23:55,0,NaN,2,6,1,1,2026-07-17 23:55

In [17]:
messages_df = messages_df.merge(user_business_history_df, how="left", on=["user_id", "business_id"])
messages_df.columns

Index(['message_id', 'user_id', 'message_conversation_type', 'group_id',
       'business_id', 'sender_user_id', 'message_created_at', 'message_text',
       'message_media_type', 'message_media_id', 'message_forwarded_count',
       'users_do_not_disturb_window', 'users_total_messages_opened_30d',
       'users_total_messages_replied_30d',
       'users_total_notifications_dismissed_30d',
       'users_total_messages_reported_30d', 'group_role', 'group_joined_at',
       'group_messages_sent_30d', 'group_messages_read_30d',
       'group_replies_sent_30d', 'group_notifications_dismissed_30d',
       'group_muted_by_user', 'group_name', 'group_type', 'group_member_count',
       'group_admin_count', 'group_created_at', 'group_total_messages_30d',
       'image_id', 'image_file_path', 'business_display_name',
       'business_brand_name', 'business_category', 'is_business_verified',
       'business_official_domain', 'business_domain_used_by_sender',
       'business_account_age_days', 'business_messages_sent_30d',
       'business_user_reports_30d', 'business_domain_used_by_sender_age_days',
       'why_user_knows_business_account', 'user_business_last_activity',
       'business_allows_promotions', 'user_business_promotions_opted_out_at',
       'user_business_activity_count_180d',
       'user_business_messages_opened_30d',
       'user_business_messages_dismissed_30d',
       'user_business_messages_replied_30d', 'user_business_last_reply_at'],
      dtype='str')

In [18]:
voice_notes_data.head()

  voice_note_id               file_path
0        vn_001  media/audio/vn_001.mp3
1        vn_002  media/audio/vn_002.mp3
2        vn_003  media/audio/vn_003.mp3
3        vn_004  media/audio/vn_004.mp3
4        vn_005  media/audio/vn_005.mp3

In [19]:
voice_notes_df = voice_notes_data.copy(deep=True)
voice_notes_df.rename(columns={"file_path":"voice_note_file_path"}, inplace=True)

In [20]:
messages_df = messages_df.merge(voice_notes_df, how="left", left_on = "message_media_id", right_on = "voice_note_id")

In [21]:
messages_df.columns

Index(['message_id', 'user_id', 'message_conversation_type', 'group_id',
       'business_id', 'sender_user_id', 'message_created_at', 'message_text',
       'message_media_type', 'message_media_id', 'message_forwarded_count',
       'users_do_not_disturb_window', 'users_total_messages_opened_30d',
       'users_total_messages_replied_30d',
       'users_total_notifications_dismissed_30d',
       'users_total_messages_reported_30d', 'group_role', 'group_joined_at',
       'group_messages_sent_30d', 'group_messages_read_30d',
       'group_replies_sent_30d', 'group_notifications_dismissed_30d',
       'group_muted_by_user', 'group_name', 'group_type', 'group_member_count',
       'group_admin_count', 'group_created_at', 'group_total_messages_30d',
       'image_id', 'image_file_path', 'business_display_name',
       'business_brand_name', 'business_category', 'is_business_verified',
       'business_official_domain', 'business_domain_used_by_sender',
       'business_account_age_days', 'business_messages_sent_30d',
       'business_user_reports_30d', 'business_domain_used_by_sender_age_days',
       'why_user_knows_business_account', 'user_business_last_activity',
       'business_allows_promotions', 'user_business_promotions_opted_out_at',
       'user_business_activity_count_180d',
       'user_business_messages_opened_30d',
       'user_business_messages_dismissed_30d',
       'user_business_messages_replied_30d', 'user_business_last_reply_at',
       'voice_note_id', 'voice_note_file_path'],
      dtype='str')

In [22]:
daily_notification_data.head()

  user_id        date  notifications_sent  notifications_dismissed
0   u_001  2026-07-04                   2                        1
1   u_001  2026-07-05                   2                        1
2   u_001  2026-07-06                   7                        1
3   u_001  2026-07-07                   5                        1
4   u_001  2026-07-08                   5                        1

In [23]:
# Notification load over the latest seven days available
notification_summary = daily_notification_data.copy()
notification_summary["date"] = pd.to_datetime(notification_summary["date"])
latest_date = notification_summary["date"].max()
recent_notifications = notification_summary[
    notification_summary["date"] >= latest_date - pd.Timedelta(days=6)
]

notifications_df = (
    recent_notifications.groupby("user_id", as_index=False)
    .agg(
        notifications_sent_7d=("notifications_sent", "sum"),
        notifications_dismissed_7d=("notifications_dismissed", "sum"),
    )
)

In [24]:
notifications_df.head()

  user_id  notifications_sent_7d  notifications_dismissed_7d
0   u_001                     31                           7
1   u_002                     52                           9
2   u_003                     39                          11
3   u_004                     54                          13
4   u_005                     44                          16

In [25]:
messages_df = messages_df.merge(notifications_df, how="left", on="user_id")
messages_df.columns

Index(['message_id', 'user_id', 'message_conversation_type', 'group_id',
       'business_id', 'sender_user_id', 'message_created_at', 'message_text',
       'message_media_type', 'message_media_id', 'message_forwarded_count',
       'users_do_not_disturb_window', 'users_total_messages_opened_30d',
       'users_total_messages_replied_30d',
       'users_total_notifications_dismissed_30d',
       'users_total_messages_reported_30d', 'group_role', 'group_joined_at',
       'group_messages_sent_30d', 'group_messages_read_30d',
       'group_replies_sent_30d', 'group_notifications_dismissed_30d',
       'group_muted_by_user', 'group_name', 'group_type', 'group_member_count',
       'group_admin_count', 'group_created_at', 'group_total_messages_30d',
       'image_id', 'image_file_path', 'business_display_name',
       'business_brand_name', 'business_category', 'is_business_verified',
       'business_official_domain', 'business_domain_used_by_sender',
       'business_account_age_days', 'business_messages_sent_30d',
       'business_user_reports_30d', 'business_domain_used_by_sender_age_days',
       'why_user_knows_business_account', 'user_business_last_activity',
       'business_allows_promotions', 'user_business_promotions_opted_out_at',
       'user_business_activity_count_180d',
       'user_business_messages_opened_30d',
       'user_business_messages_dismissed_30d',
       'user_business_messages_replied_30d', 'user_business_last_reply_at',
       'voice_note_id', 'voice_note_file_path', 'notifications_sent_7d',
       'notifications_dismissed_7d'],
      dtype='str')

In [26]:
messages_df.to_excel(str(DATASET_DIR) + "/messages_df.xlsx", index=False)

In [27]:
messages_df.shape

(110, 54)

In [28]:
message_events_data.head()

,user_id,message_id,message_opened,message_replied,reaction_time_minutes,notification_dismissed,muted_after_message,message_reported
0,u_011,message_0001,1,1,2.0,0,0,0
1,u_006,message_0002,1,1,2.0,0,0,0
2,u_010,message_0003,1,1,2.0,0,0,0
3,u_001,message_0004,1,1,2.0,0,0,0
4,u_003,message_0005,1,1,2.0,0,0,0

In [29]:
message_history_data.head()

,message_id,user_id,conversation_type,group_id,business_id,sender_user_id,created_at,message_text,media_type,media_id,forwarded_count
0,message_0107,u_008,business,NaN,business_036,NaN,2026-05-23 17:46,Delivery failed. Pay small reattempt fee at am...,NaN,NaN,0
1,message_0029,u_011,group,group_002,NaN,u_043,2026-05-26 17:57,Admin reminder: maintenance only through app/o...,NaN,NaN,0
2,message_0231,u_032,personal,NaN,NaN,u_048,2026-06-08 07:08,"Hi, the kurta set is still available. I can ke...",NaN,NaN,0
3,message_0080,u_003,group,group_016,NaN,u_051,2026-03-18 17:03,Good morning. Stay positive and send this to t...,NaN,NaN,12
4,message_0028,u_001,business,NaN,business_036,NaN,2026-05-16 12:52,Delivery attempt could not be completed.\n\nA ...,NaN,NaN,0

In [30]:
message_history_df = message_history_data.copy(deep=True)
message_history_df["created_at"] = pd.to_datetime(message_history_df["created_at"])
#message_history_df.head()
message_history_df.rename(columns={"created_at":"message_history_created_at","media_id":"message_history_media_id","media_type":"message_history_media_type","forwarded_count":"message_history_forwarded_count", "conversation_type":"message_history_conversation_type"}, inplace=True)
message_history_df = message_history_df.merge(images_df, how="left", left_on="message_history_media_id", right_on="image_id")
message_history_df = message_history_df.merge(voice_notes_df, how="left", left_on="message_history_media_id", right_on="voice_note_id")
message_history_df.head()

,message_id,user_id,message_history_conversation_type,group_id,business_id,sender_user_id,message_history_created_at,message_text,message_history_media_type,message_history_media_id,message_history_forwarded_count,image_id,image_file_path,voice_note_id,voice_note_file_path
0,message_0107,u_008,business,NaN,business_036,NaN,2026-05-23 17:46:00,Delivery failed. Pay small reattempt fee at am...,NaN,NaN,0,NaN,NaN,NaN,NaN
1,message_0029,u_011,group,group_002,NaN,u_043,2026-05-26 17:57:00,Admin reminder: maintenance only through app/o...,NaN,NaN,0,NaN,NaN,NaN,NaN
2,message_0231,u_032,personal,NaN,NaN,u_048,2026-06-08 07:08:00,"Hi, the kurta set is still available. I can ke...",NaN,NaN,0,NaN,NaN,NaN,NaN
3,message_0080,u_003,group,group_016,NaN,u_051,2026-03-18 17:03:00,Good morning. Stay positive and send this to t...,NaN,NaN,12,NaN,NaN,NaN,NaN
4,message_0028,u_001,business,NaN,business_036,NaN,2026-05-16 12:52:00,Delivery attempt could not be completed.\n\nA ...,NaN,NaN,0,NaN,NaN,NaN,NaN

In [31]:
message_history_df.head()

,message_id,user_id,message_history_conversation_type,group_id,business_id,sender_user_id,message_history_created_at,message_text,message_history_media_type,message_history_media_id,message_history_forwarded_count,image_id,image_file_path,voice_note_id,voice_note_file_path
0,message_0107,u_008,business,NaN,business_036,NaN,2026-05-23 17:46:00,Delivery failed. Pay small reattempt fee at am...,NaN,NaN,0,NaN,NaN,NaN,NaN
1,message_0029,u_011,group,group_002,NaN,u_043,2026-05-26 17:57:00,Admin reminder: maintenance only through app/o...,NaN,NaN,0,NaN,NaN,NaN,NaN
2,message_0231,u_032,personal,NaN,NaN,u_048,2026-06-08 07:08:00,"Hi, the kurta set is still available. I can ke...",NaN,NaN,0,NaN,NaN,NaN,NaN
3,message_0080,u_003,group,group_016,NaN,u_051,2026-03-18 17:03:00,Good morning. Stay positive and send this to t...,NaN,NaN,12,NaN,NaN,NaN,NaN
4,message_0028,u_001,business,NaN,business_036,NaN,2026-05-16 12:52:00,Delivery attempt could not be completed.\n\nA ...,NaN,NaN,0,NaN,NaN,NaN,NaN

In [32]:
message_history_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 412 entries, 0 to 411
Data columns (total 15 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   message_id                         412 non-null    str
 1   user_id                            412 non-null    str
 2   message_history_conversation_type  412 non-null    str
 3   group_id                           208 non-null    str
 4   business_id                        155 non-null    str
 5   sender_user_id                     257 non-null    str
 6   message_history_created_at         412 non-null    datetime64[us]
 7   message_text                       408 non-null    str
 8   message_history_media_type         23 non-null     str
 9   message_history_media_id           23 non-null     str
 10  message_history_forwarded_count    412 non-null    int64
 11  image_id                           19 non-null     str
 12  image_file_path                    19 non-null     str
 13  voice_note_id                      4 non-null      str
 14  voice_note_file_path               4 non-null      str
dtypes: datetime64[us](1), int64(1), str(13)
memory usage: 48.4 KB

In [33]:
message_events_df = message_events_data.copy(deep=True)
message_events_df.head()

,user_id,message_id,message_opened,message_replied,reaction_time_minutes,notification_dismissed,muted_after_message,message_reported
0,u_011,message_0001,1,1,2.0,0,0,0
1,u_006,message_0002,1,1,2.0,0,0,0
2,u_010,message_0003,1,1,2.0,0,0,0
3,u_001,message_0004,1,1,2.0,0,0,0
4,u_003,message_0005,1,1,2.0,0,0,0

In [34]:
message_events_df.rename(columns={"reaction_time_minutes":"message_event_reaction_time_minutes","notification_dismissed":"message_event_notification_dismissed","muted_after_message":"message_event_muted_after_message","message_reported":"message_event_reported"}, inplace=True)
message_events_df.head()

,user_id,message_id,message_opened,message_replied,message_event_reaction_time_minutes,message_event_notification_dismissed,message_event_muted_after_message,message_event_reported
0,u_011,message_0001,1,1,2.0,0,0,0
1,u_006,message_0002,1,1,2.0,0,0,0
2,u_010,message_0003,1,1,2.0,0,0,0
3,u_001,message_0004,1,1,2.0,0,0,0
4,u_003,message_0005,1,1,2.0,0,0,0

In [35]:
message_history_df = message_history_df.merge(message_events_df, how="left", on=["message_id","user_id"])
message_history_df.head()

,message_id,user_id,message_history_conversation_type,group_id,business_id,sender_user_id,message_history_created_at,message_text,message_history_media_type,message_history_media_id,...,image_id,image_file_path,voice_note_id,voice_note_file_path,message_opened,message_replied,message_event_reaction_time_minutes,message_event_notification_dismissed,message_event_muted_after_message,message_event_reported
0,message_0107,u_008,business,NaN,business_036,NaN,2026-05-23 17:46:00,Delivery failed. Pay small reattempt fee at am...,NaN,NaN,...,NaN,NaN,NaN,NaN,0,0,NaN,1,1,1
1,message_0029,u_011,group,group_002,NaN,u_043,2026-05-26 17:57:00,Admin reminder: maintenance only through app/o...,NaN,NaN,...,NaN,NaN,NaN,NaN,1,1,2.0,0,0,0
2,message_0231,u_032,personal,NaN,NaN,u_048,2026-06-08 07:08:00,"Hi, the kurta set is still available. I can ke...",NaN,NaN,...,NaN,NaN,NaN,NaN,1,1,2.0,0,0,0
3,message_0080,u_003,group,group_016,NaN,u_051,2026-03-18 17:03:00,Good morning. Stay positive and send this to t...,NaN,NaN,...,NaN,NaN,NaN,NaN,0,0,NaN,1,1,0
4,message_0028,u_001,business,NaN,business_036,NaN,2026-05-16 12:52:00,Delivery attempt could not be completed.\n\nA ...,NaN,NaN,...,NaN,NaN,NaN,NaN,0,0,NaN,1,1,1

In [36]:
message_history_df.columns

Index(['message_id', 'user_id', 'message_history_conversation_type',
       'group_id', 'business_id', 'sender_user_id',
       'message_history_created_at', 'message_text',
       'message_history_media_type', 'message_history_media_id',
       'message_history_forwarded_count', 'image_id', 'image_file_path',
       'voice_note_id', 'voice_note_file_path', 'message_opened',
       'message_replied', 'message_event_reaction_time_minutes',
       'message_event_notification_dismissed',
       'message_event_muted_after_message', 'message_event_reported'],
      dtype='str')

In [37]:
cols_to_fill = ["message_event_reaction_time_minutes", "message_event_notification_dismissed", "message_event_muted_after_message", "message_event_reported"]
message_history_df[cols_to_fill] = message_history_df[cols_to_fill].fillna(0).astype(int)

In [38]:
message_history_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 412 entries, 0 to 411
Data columns (total 21 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   message_id                            412 non-null    str
 1   user_id                               412 non-null    str
 2   message_history_conversation_type     412 non-null    str
 3   group_id                              208 non-null    str
 4   business_id                           155 non-null    str
 5   sender_user_id                        257 non-null    str
 6   message_history_created_at            412 non-null    datetime64[us]
 7   message_text                          408 non-null    str
 8   message_history_media_type            23 non-null     str
 9   message_history_media_id              23 non-null     str
 10  message_history_forwarded_count       412 non-null    int64
 11  image_id                              19 non-null     str
 12  image_file_path                       19 non-null     str
 13  voice_note_id                         4 non-null      str
 14  voice_note_file_path                  4 non-null      str
 15  message_opened                        412 non-null    int64
 16  message_replied                       412 non-null    int64
 17  message_event_reaction_time_minutes   412 non-null    int64
 18  message_event_notification_dismissed  412 non-null    int64
 19  message_event_muted_after_message     412 non-null    int64
 20  message_event_reported                412 non-null    int64
dtypes: datetime64[us](1), int64(7), str(13)
memory usage: 67.7 KB

In [39]:
group_interaction_summary = message_history_df.groupby(["group_id", "user_id"]).agg(
    total_group_messages_sent=("message_id", "count"),
    total_group_messages_opened=("message_opened", "sum"),
    total_group_messages_replied=("message_replied", "sum"),
    total_group_messages_dismissed=("message_event_notification_dismissed", "sum"),
    total_group_messages_muted=("message_event_muted_after_message", "sum"),
    total_group_messages_reported=("message_event_reported", "sum")).reset_index()
group_interaction_summary.head()

,group_id,user_id,total_group_messages_sent,total_group_messages_opened,total_group_messages_replied,total_group_messages_dismissed,total_group_messages_muted,total_group_messages_reported
0,group_001,u_001,13,2,2,11,11,0
1,group_001,u_002,1,1,0,0,0,0
2,group_001,u_003,5,0,0,5,5,0
3,group_001,u_007,3,1,0,2,2,0
4,group_002,u_001,3,3,3,0,0,0

In [40]:
business_interaction_summary = message_history_df.groupby(["business_id", "user_id"]).agg(
    total_business_messages_sent=("message_id", "count"),
    total_business_messages_opened=("message_opened", "sum"),
    total_business_messages_replied=("message_replied", "sum"),
    total_business_messages_dismissed=("message_event_notification_dismissed", "sum"),
    total_business_messages_muted=("message_event_muted_after_message", "sum"),
    total_business_messages_reported=("message_event_reported", "sum")).reset_index()

business_interaction_summary.head()

,business_id,user_id,total_business_messages_sent,total_business_messages_opened,total_business_messages_replied,total_business_messages_dismissed,total_business_messages_muted,total_business_messages_reported
0,business_001,u_001,4,4,4,0,0,0
1,business_001,u_008,1,1,1,0,0,0
2,business_001,u_010,5,5,5,0,0,0
3,business_001,u_020,1,1,1,0,0,0
4,business_001,u_029,1,1,1,0,0,0

In [41]:
sender_interaction_summary = message_history_df.groupby(["sender_user_id", "user_id"]).agg(
    total_sender_messages_sent=("message_id", "count"),
    total_sender_messages_opened=("message_opened", "sum"),
    total_sender_messages_replied=("message_replied", "sum"),
    total_sender_messages_dismissed=("message_event_notification_dismissed", "sum"),
    total_sender_messages_muted=("message_event_muted_after_message", "sum"),
    total_sender_messages_reported=("message_event_reported", "sum")).reset_index()

sender_interaction_summary.head()

,sender_user_id,user_id,total_sender_messages_sent,total_sender_messages_opened,total_sender_messages_replied,total_sender_messages_dismissed,total_sender_messages_muted,total_sender_messages_reported
0,u_041,u_001,6,6,4,0,0,0
1,u_041,u_005,2,0,0,2,2,2
2,u_041,u_007,2,2,1,0,0,0
3,u_041,u_009,1,1,1,0,0,0
4,u_041,u_012,2,2,0,0,0,0

In [42]:
messages_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 54 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   message_id                               110 non-null    str
 1   user_id                                  110 non-null    str
 2   message_conversation_type                110 non-null    str
 3   group_id                                 63 non-null     str
 4   business_id                              30 non-null     str
 5   sender_user_id                           80 non-null     str
 6   message_created_at                       110 non-null    str
 7   message_text                             102 non-null    str
 8   message_media_type                       23 non-null     str
 9   message_media_id                         23 non-null     str
 10  message_forwarded_count                  110 non-null    int64
 11  users_do_not_disturb_window              110 non-null    str
 12  users_total_messages_opened_30d          110 non-null    int64
 13  users_total_messages_replied_30d         110 non-null    int64
 14  users_total_notifications_dismissed_30d  110 non-null    int64
 15  users_total_messages_reported_30d        110 non-null    int64
 16  group_role                               63 non-null     str
 17  group_joined_at                          63 non-null     str
 18  group_messages_sent_30d                  63 non-null     float64
 19  group_messages_read_30d                  63 non-null     float64
 20  group_replies_sent_30d                   63 non-null     float64
 21  group_notifications_dismissed_30d        63 non-null     float64
 22  group_muted_by_user                      63 non-null     float64
 23  group_name                               63 non-null     str
 24  group_type                               63 non-null     str
 25  group_member_count                       63 non-null     float64
 26  group_admin_count                        63 non-null     float64
 27  group_created_at                         63 non-null     str
 28  group_total_messages_30d                 63 non-null     float64
 29  image_id                                 15 non-null     str
 30  image_file_path                          15 non-null     str
 31  business_display_name                    30 non-null     str
 32  business_brand_name                      30 non-null     str
 33  business_category                        30 non-null     str
 34  is_business_verified                     30 non-null     float64
 35  business_official_domain                 29 non-null     str
 36  business_domain_used_by_sender           30 non-null     str
 37  business_account_age_days                30 non-null     float64
 38  business_messages_sent_30d               30 non-null     float64
 39  business_user_reports_30d                30 non-null     float64
 40  business_domain_used_by_sender_age_days  30 non-null     float64
 41  why_user_knows_business_account          19 non-null     str
 42  user_business_last_activity              19 non-null     str
 43  business_allows_promotions               19 non-null     float64
 44  user_business_promotions_opted_out_at    6 non-null      str
 45  user_business_activity_count_180d        19 non-null     float64
 46  user_business_messages_opened_30d        19 non-null     float64
 47  user_business_messages_dismissed_30d     19 non-null     float64
 48  user_business_messages_replied_30d       19 non-null     float64
 49  user_business_last_reply_at              9 non-null      str
 50  voice_note_id                            8 non-null      str
 51  voice_note_file_path                     8 non-null      str
 52  notifications_sent_7d                    110 non-null    int64
 53  notifications_dismissed_7d               110 non-null    int64
dtypes: float64(18), int64(7), str(29)
memory usage: 46.5 KB

In [43]:
messages_df = messages_df.merge(group_interaction_summary, how="left", on=["group_id", "user_id"])
messages_df = messages_df.merge(business_interaction_summary, how="left", on=["business_id", "user_id"])
messages_df = messages_df.merge(sender_interaction_summary, how="left", on=["sender_user_id", "user_id"])
messages_df.to_excel(DATASET_DIR / "modified_data" / "final_dataset.xlsx", index=False)

In [44]:
messages_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 72 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   message_id                               110 non-null    str
 1   user_id                                  110 non-null    str
 2   message_conversation_type                110 non-null    str
 3   group_id                                 63 non-null     str
 4   business_id                              30 non-null     str
 5   sender_user_id                           80 non-null     str
 6   message_created_at                       110 non-null    str
 7   message_text                             102 non-null    str
 8   message_media_type                       23 non-null     str
 9   message_media_id                         23 non-null     str
 10  message_forwarded_count                  110 non-null    int64
 11  users_do_not_disturb_window              110 non-null    str
 12  users_total_messages_opened_30d          110 non-null    int64
 13  users_total_messages_replied_30d         110 non-null    int64
 14  users_total_notifications_dismissed_30d  110 non-null    int64
 15  users_total_messages_reported_30d        110 non-null    int64
 16  group_role                               63 non-null     str
 17  group_joined_at                          63 non-null     str
 18  group_messages_sent_30d                  63 non-null     float64
 19  group_messages_read_30d                  63 non-null     float64
 20  group_replies_sent_30d                   63 non-null     float64
 21  group_notifications_dismissed_30d        63 non-null     float64
 22  group_muted_by_user                      63 non-null     float64
 23  group_name                               63 non-null     str
 24  group_type                               63 non-null     str
 25  group_member_count                       63 non-null     float64
 26  group_admin_count                        63 non-null     float64
 27  group_created_at                         63 non-null     str
 28  group_total_messages_30d                 63 non-null     float64
 29  image_id                                 15 non-null     str
 30  image_file_path                          15 non-null     str
 31  business_display_name                    30 non-null     str
 32  business_brand_name                      30 non-null     str
 33  business_category                        30 non-null     str
 34  is_business_verified                     30 non-null     float64
 35  business_official_domain                 29 non-null     str
 36  business_domain_used_by_sender           30 non-null     str
 37  business_account_age_days                30 non-null     float64
 38  business_messages_sent_30d               30 non-null     float64
 39  business_user_reports_30d                30 non-null     float64
 40  business_domain_used_by_sender_age_days  30 non-null     float64
 41  why_user_knows_business_account          19 non-null     str
 42  user_business_last_activity              19 non-null     str
 43  business_allows_promotions               19 non-null     float64
 44  user_business_promotions_opted_out_at    6 non-null      str
 45  user_business_activity_count_180d        19 non-null     float64
 46  user_business_messages_opened_30d        19 non-null     float64
 47  user_business_messages_dismissed_30d     19 non-null     float64
 48  user_business_messages_replied_30d       19 non-null     float64
 49  user_business_last_reply_at              9 non-null      str
 50  voice_note_id                            8 non-null      str
 51  voice_note_file_path                     8 non-null      str
 52  notifications_sent_7d                    110 non-null    int64
 53  notifications_dismissed_7d               110 non-null    int64
 54  total_group_messages_sent                63 non-null     float64
 55  total_group_messages_opened              63 non-null     float64
 56  total_group_messages_replied             63 non-null     float64
 57  total_group_messages_dismissed           63 non-null     float64
 58  total_group_messages_muted               63 non-null     float64
 59  total_group_messages_reported            63 non-null     float64
 60  total_business_messages_sent             27 non-null     float64
 61  total_business_messages_opened           27 non-null     float64
 62  total_business_messages_replied          27 non-null     float64
 63  total_business_messages_dismissed        27 non-null     float64
 64  total_business_messages_muted            27 non-null     float64
 65  total_business_messages_reported         27 non-null     float64
 66  total_sender_messages_sent               77 non-null     float64
 67  total_sender_messages_opened             77 non-null     float64
 68  total_sender_messages_replied            77 non-null     float64
 69  total_sender_messages_dismissed          77 non-null     float64
 70  total_sender_messages_muted              77 non-null     float64
 71  total_sender_messages_reported           77 non-null     float64
dtypes: float64(36), int64(7), str(29)
memory usage: 62.0 KB